---
# tasks file for install_mendix
# This installation is specific to RedHat / Centos
#
# 1. Copy Mendix rpm repo to /etc/yum.repos.d/mendix.repo
#   1.0 install required packages first - yaml, httplib2 - from EPEL
#   1.1 yum install mendix
# 2. Add a mendix user "myapp"
# 3. Create a directory for 1st application in /srv/mendix/myapp
# 4. Create directory /home/myapp/.m2ee
# 5. Copy /usr/share/doc/user-specific-m2ee.yaml to /home/myapp/.m2ee/m2ee.yaml
#
# 1. Copy Mendix repo file to target
- name: copy mendix repo discription to /etc/yum.repos.d/mendix.repo
  copy:   src="mendix.repo" dest="/etc/yum.repos.d/mendix.repo" owner=root mode=0644
  tags:   install_mendix
#
# Install the EPEL repos for Mendix dependencies
- name: Get EPEL repos
  get_url: url='{{epel_repo}}' dest='{{epel_repo_rpm}}'
  tags:  install_mendix
#
# Install the EPEL repo via rpm
- name: Install the EPEL repo via rpm
  yum:  name='{{epel_repo_rpm}}' state=present
  tags:  install_mendix
#
# 1.1 Install m2ee-tools
- name: Install m2ee-tools and dependencies from mendix repo
  yum:    name='{{item}}' state=installed
  with_items: '{{mendix_packages}}'
  tags:   install_mendix
#
# Create the Mendix user group
- name: Create the Mendix user group
  group: name='{{mendix_user}}' state=present
  tags: install_mendix
# 2. Create mendix app user "myapp"
- name:     create user '{{mendix_user}}'
  user:   name='{{mendix_user}}' password='{{mendix_password}}' group='{{mendix_user}}' comment="Mendix user {{mendix_user}}"
  tags:   install_mendix
#
# 3. Create application directory
- name: Create the 1st application directory structure
  file:   path=/srv/mendix/{{ item }} owner='{{mendix_user}}' mode=0755 state=directory
  with_items: '{{mendix_dir_list }}'
  tags:   install_mendix
#
# 4. Create hidden dir .m2ee in /home/'{{mendix_user}}'
- name: Create hidden dir .m2ee in Mendix user homedir
  file:   path="/home/{{mendix_user}}/.m2ee" owner='{{mendix_user}}' state=directory
  tags:   install_mendix
#
# find the full path to the sample m2ee.yaml file
#
- name: find and register the path to the sample m2ee.yaml file
  shell:    find /usr/share/doc -name 'user-specific-m2ee.yaml' -print
  register: path_to_sample
  tags:     install_mendix
# 5. Copy sample m2ee.yaml to myapp/.m2ee/m2ee.yaml **New - use synchronize
- name: Copy /usr/share/doc/user-specific-m2ee.yaml to /home/'{{mendix_user}}'/.m2ee/
  copy: remote_src=true src='{{path_to_sample.stdout}}' dest="/home/{{mendix_user}}/.m2ee/m2ee.yaml" owner='{{mendix_user}}' group='{{mendix_user}}'
  tags:   install_mendix
#
# Copy the m2ee system wide sample yaml to /etc/m2ee
#
- name: Create /etc/m2ee
  file:  path="/etc/m2ee" state=directory
  tags:  install_mendix
#
- name: Find the full path to the system wide yaml file
  shell:  find /usr/share/doc -name 'system-wide-m2ee.yaml' -print
  register: path_to_system_wide
  tags:  install_mendix
#
- name: Copy the system wide sample to /etc/m2ee
  copy:  remote_src=true src='{{path_to_system_wide.stdout}}' dest="/etc/m2ee/m2ee.yaml"
  tags:  install_mendix
#
# fin