---
# vars file for appd_controller
# look for vars in groupo_vars/controller
# Initial controller settings. Added to response.varfile and passed to setup:

mysql_root_password: singcontroller
root_password: vagrant
first_username: user1
first_password: welcome
home_dir: /opt/AppDynamics


#
# DO NOT CHANGE BELOW THIS LINE
#

nexus_url: "http://lnx-nexus1.corp.appdynamics.com/nexus/content/repositories/releases/{{ nexus_build }}/setup-64bit-linux/{{ nexus_version }}/"
md5_url: "{{ nexus_url }}/setup-64bit-linux-{{ nexus_version }}.sh.md5"
installer_url: "{{ nexus_url }}/setup-64bit-linux-{{ nexus_version }}.sh"

installer: /tmp/controller_64bit_linux.sh
install_dir: "{{ home_dir }}/Controller"
