---

-   name: Add the OS specific variables
    include_vars: "{{ ansible_os_family }}.yml"
    tags: ntp
    
-   name: Install the required packages in RedHat derivatives
    yum: name={{ item }} state=installed
    with_items: '{{ntp_pkgs}}'
    when: ansible_os_family == "RedHat"
    tags: ntp
    
-   name: Install the required packages in Debian derivatives
    apt: name={{ item }} state=installed update_cache=yes
    with_items: '{{ntp_pkgs}}'
    when: ansible_os_family == "Debian"
    tags: ntp
#
# Set the machine's time zone - timedatectl is available on Ubuntu 14
- name: RedHat set time zone
  command:  timedatectl set-timezone America/New_York
#  when: ansible_os_family == "RedHat"
  tags: ntp
#
# Disable the machine's RTC usage  
- name:  RedHat disable RTC
  command:  timedatectl set-local-rtc 0
#  when: ansible_os_family == "RedHat"
  tags: ntp
#       
-   name: Copy the ntp.conf template file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    tags: ntp
    notify:
    - restart ntp
    
