# Moving MachineAgent files to the remote host
# Source file is in files/ roles dir
appagent_srcFile: AppServerAgent.zip
appagent_destFolder: /opt/appdynamics/appagent/
appagent_destFile: AppServerAgent.zip
#
appagent_processName: javaagent.jar
#
## Restart the machineagent switch
# This should be prompted for - somehow- vars_prompt:
##
appagent_restart: "y"
##
#
# Define Controller-info.xml attributes
# use named backreferences when the content following the 
#  backreference is numeric - or just always use them.
#
vars_controllerInfo:
  - { varname: '(?P<contr>^[\s]*<controller-host>)', value: '\g<contr>{{ controller_hostName }}</controller-host>' }
  - { varname: '(?P<port>^[\s]*<controller-port>)', value: '\g<port>{{ controller_port }}</controller-port>' }
  - { varname: '(?P<ssl>^[\s]*<controller-ssl-enabled>)', value: '\g<ssl>false</controller-ssl-enabled>' }
  - { varname: '(?P<orc>^[\s]*<enable-orchestration>)', value: '\g<orc>false</enable-orchestration>' }
  - { varname: '(?P<account>^[\s]*<account-name>)', value: '\g<account></account-name>' }
  - { varname: '(?P<key>^[\s]*<account-access-key>)', value: '\g<key>{{ agent_accountAccessKey }}</account-access-key>' }
  - { varname: '(?P<app>^[\s]*<application-name>)', value: '\g<app>{{ applicationName }}</application-name>' }
  - { varname: '(?P<tier>^[\s]*<tier-name>)', value: '\g<tier>{{ agent_tierName }}</tier-name>' }
  - { varname: '(?P<node>^[\s]*<node-name>)', value: '\g<node>{{ agent_nodeName }}</node-name>' }
  - { varname: '(?P<force>^[\s]*<force-agent-registration>)', value: '\g<force>true</force-agent-registration>' }
#
#
