---
#
# Configure AppD for System init
#
- name: Install init script
  copy: src=init.d.sh dest="{{ install_dir }}/bin" mode=0755 
  become: yes
  become_user: appd
  tags: appdc

- name: Link init script into init.d folder
  file: src="{{ install_dir }}/bin/init.d.sh" dest="/etc/init.d/controller" state=link 
  become: yes
  become_user: root
  become_method: sudo
  tags: appdc

- name: Register init script
  command: /sbin/chkconfig --add controller
  become: yes
  become_user: root
  become_method: sudo
  tags: appdc

- name: Add controller to standard run levels
  command: /sbin/chkconfig --level 2345 controller on
  become: yes
  become_user: root
  become_method: sudo
  tags: appdc
