---
#
# Installs AppD Controller using template; Copies license file
#
- name: Copy response file
  template: src=response.varfile.j2 dest=/tmp/response.varfile mode=0644
  tags: appdc

- name: Install controller 
  command: "{{ installer }} -q -varfile /tmp/response.varfile"
  become: yes
  become_user: appd
  become_method: sudo
  async: 5000
  poll: 0
#  register: appdc_status
  tags: appdc

#- name: Check install Status.
#  async_status: 
#    jid: "{{ appdc_status.ansible_job_id }}"
#  register: job_result
#  until: job_result.finished
#  retries: 30
#
# Wait for Controller directory to be present
# 
- name: Wait for Controller directory
  wait_for: "{{ install_dir }}/install.log"
  tags: appdc

- name: Install test license 
  copy: src=license.lic dest="{{ install_dir }}/license.lic" owner=appd
#  become: yes
#  become_user: appd
#  become_method: sudo
  tags: appdc
