---
#
# This playbook installs and configures mendix on remote machines (centos only)
#

- name: install ntp
  hosts:  mendix
  become: true
  become_method:  sudo
#
  roles:
    - ntp
    
- name: install m2ee tools
  hosts:  mendix
  become: true
  become_method:  sudo
#
  roles:
    - install_mendix
#
- name: install appdynamics machine agent
  hosts:  mendix
  become: true
  become_method: sudo
#  
  roles:
    - machineagent
#
- name: install appdynamics app agent
  hosts: mendix
  become: true
  become_method: sudo
#
  roles:
    - appagent
#
- name: install PostgreSQL
  hosts: mendix
  become: true
  become_method: sudo
#
  roles:
    - postgresql
#
- name: Add Mendix DB table and DB user
  hosts: mendix
  become: true
  become_method: sudo
#
  roles:
    - mendixdb

# fin