---
# tasks file for mendixdb
- name: Database | Create Mendix Database
  become_user: postgres
  become: yes
  postgresql_db: name={{ dbname }}
  tags: mendixdb
#
- name: Database | Create Mendix become_user
  become_user: postgres
  become: yes
  postgresql_user: encrypted=yes db={{ dbname }} name={{dbuser}}  password={{dbpassword}} role_attr_flags=SUPERUSER priv=ALL state=present
  tags: mendixdb
# fin  