---
# vars file for install_mendix
mendix_dir_list:
  - myapp
  - myapp/runtime
  - myapp/web
  - myapp/model
  - myapp/data
  - myapp/data/database
  - myapp/data/files
  - myapp/data/model-upload
  - myapp/data/tmp

  #
mendix_packages:
    - python-httplib2
    - PyYAML
    - m2ee-tools
    - yum-utils
# fin
