---
# vars file for install_mendix
mendix_dir_list:
  - "{{ mendix_user }}"
  - "{{ mendix_user }}/runtime"
  - "{{ mendix_user }}/web"
  - "{{ mendix_user }}/model"
  - "{{ mendix_user }}/data"
  - "{{ mendix_user }}/data/database"
  - "{{ mendix_user }}/data/files"
  - "{{ mendix_user }}/data/model-upload"
  - "{{ mendix_user }}/data/tmp"

  #
#
# Required packages for Mendix environment
# python-psycopg2 is required for the ansible postgresql_db module
#  creates databases and users
#
mendix_packages:
    - python-httplib2
    - PyYAML
    - m2ee-tools
    - yum-utils
    - java-1.8.0-openjdk
    - python-psycopg2
# fin
